# Generated by Django 3.2.19 on 2023-06-09 06:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/sandrabergstrom/image/upload/v1685538683/default/default_profile_vbamal.jpg', max_length=255, verbose_name='image'),
        ),
    ]
